# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
