# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170313_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tovar',
            options={'ordering': ['tovar_name'], 'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='tovar_img',
            options={'verbose_name': 'фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='tovar_inphoto',
            options={'ordering': ['tovarinphoto_proizv'], 'verbose_name': 'характеристику', 'verbose_name_plural': 'Характеристики'},
        ),
    ]
