# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20170314_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar_inphoto',
            name='tovarinphoto_sim',
            field=models.CharField(default=1, max_length=200, verbose_name='Количество сим-карт'),
            preserve_default=False,
        ),
    ]
