# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20170325_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar_img',
            name='tovar_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tovar_img',
            name='tovar_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
