# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20170325_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar_img',
            name='tovar_info3',
            field=models.TextField(blank=True, verbose_name='Описание3'),
        ),
        migrations.AddField(
            model_name='tovar_img',
            name='tovar_info4',
            field=models.TextField(blank=True, verbose_name='Описание4'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='tovar_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name="Название(указать обязательно,к примеру 'Meizu')"),
        ),
    ]
