# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170325_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar_img',
            name='tovar_info5',
            field=models.TextField(blank=True, verbose_name='Описание5'),
        ),
    ]
