# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20170326_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar_img',
            name='tovar_video',
            field=models.CharField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', max_length=200),
        ),
    ]
