# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20170327_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='tovar_image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='tovar_img',
            name='tovar_image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='tovar_img',
            name='tovar_image1',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара1'),
        ),
        migrations.AlterField(
            model_name='tovar_img',
            name='tovar_image10',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара10'),
        ),
        migrations.AlterField(
            model_name='tovar_img',
            name='tovar_image11',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара11'),
        ),
        migrations.AlterField(
            model_name='tovar_img',
            name='tovar_image2',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара2'),
        ),
        migrations.AlterField(
            model_name='tovar_img',
            name='tovar_image3',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара3'),
        ),
        migrations.AlterField(
            model_name='tovar_img',
            name='tovar_image4',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара4'),
        ),
        migrations.AlterField(
            model_name='tovar_img',
            name='tovar_image5',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара5'),
        ),
        migrations.AlterField(
            model_name='tovar_img',
            name='tovar_image6',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара6'),
        ),
        migrations.AlterField(
            model_name='tovar_img',
            name='tovar_image7',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара7'),
        ),
        migrations.AlterField(
            model_name='tovar_img',
            name='tovar_image8',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара8'),
        ),
        migrations.AlterField(
            model_name='tovar_img',
            name='tovar_image9',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара9'),
        ),
    ]
